# Arquivo de Workflow do GitHub Actions para o Bot de Notícias

name: Automação do Bot de Notícias

on:
  schedule:
    # Roda a cada 2 horas (UTC)
    - cron: '0 */2 * * *'

  workflow_dispatch:

jobs:
  run-news-bot:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: 1. Baixando o código do projeto
        uses: actions/checkout@v3

      - name: 2. Configurando o ambiente Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 3. Instalando dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 4. Rodando o bot de notícias
        run: python3 main_noticias.py
        env:
          X_API_KEY: ${{ secrets.X_API_KEY }}
          X_API_SECRET: ${{ secrets.X_API_SECRET }}
          X_ACCESS_TOKEN: ${{ secrets.X_ACCESS_TOKEN }}
          X_ACCESS_TOKEN_SECRET: ${{ secrets.X_ACCESS_TOKEN_SECRET }}

      - name: 5. Commit do estado atualizado
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: Atualiza estado do bot de notícias'
          file_pattern: estado.json